/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.miniproject;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author arnavprabhale
 */
public class questionPage extends javax.swing.JFrame
{

    /**
     * Creates new form questionPage
     */
    questionPage qp;
    StudentInfo stud;
    int question_no = 1;
    ButtonGroup bgOption;
    JButton btngroup[];
    JRadioButton optionList[];
    camMonitor cm;
    
    public questionPage(StudentInfo s)
    {
        qp = this;
        initComponents();
        bgOption = new ButtonGroup();
        addButtonGroup(bgOption);
        displaybtn();
        stud = s;
        displayInfo();
        displayQuestion(question_no);
        startStopWatch(stopwatchPanel, lbltime, qp, stud);      // to start the timer
        cm = new camMonitor(lblcamera);
        
    }

    public questionPage()
    {
        qp = this;
        initComponents();
        //startStopWatch(stopwatchPanel, lbltime, qp);      // to start the timer
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        subPanel = new javax.swing.JPanel();
        questionPanel = new javax.swing.JPanel();
        lblrollno = new javax.swing.JLabel();
        lblquestion = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        cameraPanel = new javax.swing.JPanel();
        lblcamera = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        rdboption2 = new javax.swing.JRadioButton();
        rdboption3 = new javax.swing.JRadioButton();
        rdboption4 = new javax.swing.JRadioButton();
        rdboption1 = new javax.swing.JRadioButton();
        lbloptionMarked = new javax.swing.JLabel();
        qButtonPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        q3 = new javax.swing.JButton();
        q1 = new javax.swing.JButton();
        q2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        q6 = new javax.swing.JButton();
        q4 = new javax.swing.JButton();
        q5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        q9 = new javax.swing.JButton();
        q7 = new javax.swing.JButton();
        q8 = new javax.swing.JButton();
        submitPanel = new javax.swing.JPanel();
        btnnext = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        stopwatchPanel = new javax.swing.JPanel();
        lbltime = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(114, 114, 114));

        subPanel.setBackground(new java.awt.Color(107, 107, 107));
        subPanel.setToolTipText("");

        lblrollno.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        lblrollno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblrollno.setText("ROLL NUMBER");

        lblquestion.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        lblquestion.setText("QUESTION");

        lblname.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        lblname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblname.setText("Name");

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblrollno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblrollno, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblcamera.setText("Camera");

        javax.swing.GroupLayout cameraPanelLayout = new javax.swing.GroupLayout(cameraPanel);
        cameraPanel.setLayout(cameraPanelLayout);
        cameraPanelLayout.setHorizontalGroup(
            cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcamera, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        cameraPanelLayout.setVerticalGroup(
            cameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblcamera, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        rdboption2.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        rdboption2.setText("OPTION B");
        rdboption2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdboption2ActionPerformed(evt);
            }
        });

        rdboption3.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        rdboption3.setText("OPTION C");
        rdboption3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdboption3ActionPerformed(evt);
            }
        });

        rdboption4.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        rdboption4.setText("OPTION D");
        rdboption4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdboption4ActionPerformed(evt);
            }
        });

        rdboption1.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        rdboption1.setText("OPTION A");
        rdboption1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdboption1ActionPerformed(evt);
            }
        });

        lbloptionMarked.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbloptionMarked.setForeground(new java.awt.Color(0, 204, 0));
        lbloptionMarked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdboption4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(optionPanelLayout.createSequentialGroup()
                        .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbloptionMarked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdboption2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdboption3, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(rdboption1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rdboption1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdboption2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdboption3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdboption4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbloptionMarked, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        q3.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q3.setText("3");
        q3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q3ActionPerformed(evt);
            }
        });

        q1.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q1.setText("1");
        q1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q1ActionPerformed(evt);
            }
        });

        q2.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q2.setText("2");
        q2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(q3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        q6.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q6.setText("6");
        q6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q6ActionPerformed(evt);
            }
        });

        q4.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q4.setText("4");
        q4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q4ActionPerformed(evt);
            }
        });

        q5.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q5.setText("5");
        q5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        q9.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q9.setText("9");
        q9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q9ActionPerformed(evt);
            }
        });

        q7.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q7.setText("7");
        q7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q7ActionPerformed(evt);
            }
        });

        q8.setFont(new java.awt.Font("Malayalam MN", 1, 20)); // NOI18N
        q8.setText("8");
        q8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                q8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(q8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout qButtonPanelLayout = new javax.swing.GroupLayout(qButtonPanel);
        qButtonPanel.setLayout(qButtonPanelLayout);
        qButtonPanelLayout.setHorizontalGroup(
            qButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qButtonPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(qButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        qButtonPanelLayout.setVerticalGroup(
            qButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnnext.setFont(new java.awt.Font("Malayalam MN", 0, 14)); // NOI18N
        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnnextActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Malayalam MN", 0, 14)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnclearActionPerformed(evt);
            }
        });

        btnprevious.setFont(new java.awt.Font("Malayalam MN", 0, 14)); // NOI18N
        btnprevious.setText("PREVIOUS");
        btnprevious.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnpreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        lbltime.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        lbltime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltime.setText("STOPWATCH");

        javax.swing.GroupLayout stopwatchPanelLayout = new javax.swing.GroupLayout(stopwatchPanel);
        stopwatchPanel.setLayout(stopwatchPanelLayout);
        stopwatchPanelLayout.setHorizontalGroup(
            stopwatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        stopwatchPanelLayout.setVerticalGroup(
            stopwatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbltime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(questionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopwatchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(cameraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(stopwatchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(questionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnsubmit.setFont(new java.awt.Font("Malayalam MN", 0, 14)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsubmitActionPerformed
    {//GEN-HEADEREND:event_btnsubmitActionPerformed


        int res = JOptionPane.showConfirmDialog(mainPanel, "Once Submitted Can't make changes", "Confirm Submit", JOptionPane.CANCEL_OPTION);
        
        if(JOptionPane.YES_OPTION == res)
        {
            MongoClient mongo = new MongoClient("localhost", 27017);
            DB db = mongo.getDB("BloodDonation");
            DBCollection set = db.getCollection("BloodGroup");
            
            ArrayList<BasicDBObject> answer_marked = new ArrayList<>();
            for(int j = 0; j < 9; j++)
            {
                answer_marked.add(new BasicDBObject(String.valueOf(j+1), stud.optionTicked[j]));
            }
            
            BasicDBObject answer = new BasicDBObject();
            answer.put("RollNo", stud.rollno);
            answer.put("Name", stud.name);
            answer.put("test_1", answer_marked);
            set.insert(answer);
        
            
            submitPage sp = new submitPage(stud);
            sp.setVisible(true);
            qp.setVisible(false);
        }
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void rdboption4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdboption4ActionPerformed
    {//GEN-HEADEREND:event_rdboption4ActionPerformed
        optoionMarked();
        // TODO add your handling code here:
    }//GEN-LAST:event_rdboption4ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnclearActionPerformed
    {//GEN-HEADEREND:event_btnclearActionPerformed
        bgOption.clearSelection();
        optoionMarked();
        btngroup[question_no - 1].setBackground(null);
        // TODO add your handling code here:
        
        
        cm.upload();
        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnnextActionPerformed
    {//GEN-HEADEREND:event_btnnextActionPerformed
        if(question_no < 9)question_no ++;
        questionbtnPressed(question_no);
        if(stud.optionTicked[question_no - 1] == -1)
        {
            bgOption.clearSelection();
        }
        lbloptionMarked.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnextActionPerformed

    private void rdboption1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdboption1ActionPerformed
    {//GEN-HEADEREND:event_rdboption1ActionPerformed
        optoionMarked();
        // TODO add your handling code here:
    }//GEN-LAST:event_rdboption1ActionPerformed

    private void rdboption2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdboption2ActionPerformed
    {//GEN-HEADEREND:event_rdboption2ActionPerformed
        optoionMarked();
        // TODO add your handling code here:
    }//GEN-LAST:event_rdboption2ActionPerformed

    private void rdboption3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdboption3ActionPerformed
    {//GEN-HEADEREND:event_rdboption3ActionPerformed
        optoionMarked();
        // TODO add your handling code here:
    }//GEN-LAST:event_rdboption3ActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnpreviousActionPerformed
    {//GEN-HEADEREND:event_btnpreviousActionPerformed
        if(question_no > 1)question_no --;
        questionbtnPressed(question_no);
//        if(question_no  9)
//        {
//            bgOption.clearSelection();
//        }
        lbloptionMarked.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q1ActionPerformed
    {//GEN-HEADEREND:event_q1ActionPerformed
        questionbtnPressed(1);


        // TODO add your handling code here:
    }//GEN-LAST:event_q1ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q2ActionPerformed
    {//GEN-HEADEREND:event_q2ActionPerformed
        questionbtnPressed(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_q2ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q3ActionPerformed
    {//GEN-HEADEREND:event_q3ActionPerformed
        questionbtnPressed(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q4ActionPerformed
    {//GEN-HEADEREND:event_q4ActionPerformed
        questionbtnPressed(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_q4ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q5ActionPerformed
    {//GEN-HEADEREND:event_q5ActionPerformed
        questionbtnPressed(5);
        // TODO add your handling code here:
    }//GEN-LAST:event_q5ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q6ActionPerformed
    {//GEN-HEADEREND:event_q6ActionPerformed
        questionbtnPressed(6);
        // TODO add your handling code here:
    }//GEN-LAST:event_q6ActionPerformed

    private void q7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q7ActionPerformed
    {//GEN-HEADEREND:event_q7ActionPerformed
        questionbtnPressed(7);
        // TODO add your handling code here:
    }//GEN-LAST:event_q7ActionPerformed

    private void q8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q8ActionPerformed
    {//GEN-HEADEREND:event_q8ActionPerformed
        questionbtnPressed(8);
        // TODO add your handling code here:
    }//GEN-LAST:event_q8ActionPerformed

    private void q9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_q9ActionPerformed
    {//GEN-HEADEREND:event_q9ActionPerformed
        questionbtnPressed(9);
        // TODO add your handling code here:
    }//GEN-LAST:event_q9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(questionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new questionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JPanel cameraPanel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblcamera;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lbloptionMarked;
    private javax.swing.JLabel lblquestion;
    private javax.swing.JLabel lblrollno;
    private javax.swing.JLabel lbltime;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JButton q1;
    private javax.swing.JButton q2;
    private javax.swing.JButton q3;
    private javax.swing.JButton q4;
    private javax.swing.JButton q5;
    private javax.swing.JButton q6;
    private javax.swing.JButton q7;
    private javax.swing.JButton q8;
    private javax.swing.JButton q9;
    private javax.swing.JPanel qButtonPanel;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JRadioButton rdboption1;
    private javax.swing.JRadioButton rdboption2;
    private javax.swing.JRadioButton rdboption3;
    private javax.swing.JRadioButton rdboption4;
    private javax.swing.JPanel stopwatchPanel;
    private javax.swing.JPanel subPanel;
    private javax.swing.JPanel submitPanel;
    // End of variables declaration//GEN-END:variables

    private void startStopWatch(JPanel stopwatchpanel, JLabel lbltime, questionPage qp, StudentInfo stud)
    {
        
        StopWatch st = new StopWatch(stopwatchpanel, lbltime, qp, stud);
     
    }

    private void displayInfo()
    {
        
        lblname.setText(stud.name);
        lblrollno.setText(stud.rollno);
    }

    private void displayQuestion(int question_no)
    {
        btnOnQuestion();
        
        try
        {
            
            MongoClient mongo = new MongoClient("localhost", 27017);
            
            DB db = mongo.getDB("BloodDonation");
            
            DBCollection table = db.getCollection("BloodBank");
            
            DBCursor cursor = table.find();
            DBObject disp = cursor.next();
            
            
            while (cursor.hasNext()) 
            {
                double id  = (Double)disp.get("_id");
                int idd = (int)id;
                System.out.println("Step 1");
                System.out.println(question_no);
                
                if(idd == question_no)
                {
                    String questionString = (String) disp.get("question");
                    String option_1String = (String) disp.get("option_1");
                    String option_2String = (String) disp.get("option_2");
                    String option_3String = (String) disp.get("option_3");
                    String option_4String = (String) disp.get("option_4");
                    
                    questionString = "<html><p>" + questionString + "</p></html>";
                
                    lblquestion.setText(questionString);
                    rdboption1.setText(option_1String);
                    rdboption2.setText(option_2String);
                    rdboption3.setText(option_3String);
                    rdboption4.setText(option_4String);
                    break;
        
                }
                else
                {
                    disp =  cursor.next();
                }
            }
            
              
        } 
        catch (HeadlessException | NumberFormatException  e)
        {
            JOptionPane.showMessageDialog(mainPanel, "Error = " + e);
        }
    }

    private void addButtonGroup(ButtonGroup bgOption)
    {
         
        bgOption.add(rdboption1);
        bgOption.add(rdboption2);
        bgOption.add(rdboption3);
        bgOption.add(rdboption4);
    }

    private void optoionMarked()
    {
        if(rdboption1.isSelected())
        {
            stud.optionTicked[question_no - 1] = 1;
            lbloptionMarked.setText("Option A marked Successfully");
            System.out.println("option A marked");

        }
        else if(rdboption2.isSelected())
        {
            stud.optionTicked[question_no - 1] = 2;
            lbloptionMarked.setText("Option B marked Successfully");
            System.out.println("option b marked");
        }
        else if(rdboption3.isSelected())
        {
            stud.optionTicked[question_no - 1] = 3;
            lbloptionMarked.setText("Option C marked Successfully");
            System.out.println("option c marked");
        }
        else if(rdboption4.isSelected())
        {
            stud.optionTicked[question_no - 1] = 4;
            lbloptionMarked.setText("Option D marked Successfully");
            System.out.println("option d marked");
        }
        else
        {
            stud.optionTicked[question_no - 1] = -1;
            lbloptionMarked.setText("Option Unmarked Successfully");
        }
        btnColor();
        
        for(int i = 0; i < stud.optionTicked.length; i++)
        {
            System.out.print(stud.optionTicked[i] + "  ");
        }
        System.out.println();
        
    }

    private void btnColor()
    {
        
        for(int i = 0; i < 9; i++)
        {
            if(stud.optionTicked[i] != -1)
            {
                btngroup[i].setBackground(Color.GREEN);
            }
        }
    }

    private void btnOnQuestion()
    {
        for(int i = 0; i < 9; i++)
        {
            if(i == question_no - 1)
            {
                btngroup[i].setBorder(BorderFactory.createLineBorder(Color.BLUE, 3));
            }
            else
            {
                btngroup[i].setBorder(null);
            }
        }
    }

    private void displaybtn()
    {
        btngroup = new JButton[9];
        btngroup[0] = q1;
        btngroup[1] = q2;
        btngroup[2] = q3;
        btngroup[3] = q4;
        btngroup[4] = q5;
        btngroup[5] = q6;
        btngroup[6] = q7;
        btngroup[7] = q8;
        btngroup[8] = q9;
        
        optionList = new JRadioButton[4];
        optionList[0] = rdboption1;
        optionList[1] = rdboption2;
        optionList[2] = rdboption3;
        optionList[3] = rdboption4;
    }

    private void questionbtnPressed(int i)
    {
       question_no = i;
       displayQuestion(i);
       if(stud.optionTicked[i - 1] != -1)optionList[stud.optionTicked[i - 1] - 1].doClick(); 
       else
       {
           bgOption.clearSelection();
       }
       
       lbloptionMarked.setText("");
    }
}







